services:
  csvserver:
    image: infracloudio/csvserver:latest
    container_name: csvserver
    environment:
      - CSVSERVER_BORDER=Orange
    ports:
      - "9393:9300"
    volumes:
      - ./inputdata:/csvserver/inputdata:z

  prometheus:
    image: prom/prometheus:v2.45.2
    container_name: prometheus
    ports:
      - "0.0.0.0:9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:z
    depends_on:
      - csvserver



